models: # model directives, specifying the models to instantiate
  - blip2
postprocess_columns: # postprocessing directives
  - blip2-cap
additional_fields: # fields in a webdataset json to carry over into the metadata
  - uid
  - url
  - caption
  - original_width
  - original_height
  - sha256
nworkers: 2
batch_size: 512
device: 0
input_tars: "s3://s-laion/datanet_100M_pool-baselines/basic/all/seed_1/reshards_n1/0/" # brace expand suported
output_metadata_dir: "s3://s-laion/thaottn/100M_pool_blip2_captions" # can be arbitrary path - TODO: SET THIS
custom_pypath: "./custom/my_blip2.py" # if model not known, look in this python file for implementation
